name: Java CI with Gradle

# --- Triggers ---
# This workflow will run on two events:
# 1. When code is pushed to the 'main' branch.
# 2. When a pull request is created or updated that targets the 'main' branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# --- Jobs ---
# A workflow is made up of one or more jobs that can run in parallel or sequentially.
jobs:
  # This job is named 'build'
  build:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is the standard.
    runs-on: ubuntu-latest

    # The sequence of tasks that make up the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # For SonarCloud pull request analysis
        with:
          fetch-dept: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # SONARCLOUD
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}